// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/useractorrating.proto

package com.feiyu.protobuf;

public final class UserActorRatingProtos {
  private UserActorRatingProtos() {}
  public static void registerAllExtensions(
                                           com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
  // @@protoc_insertion_point(interface_extends:User)
  com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <code>optional int64 userid = 1;</code>
     */
    long getUserid();

    /**
     * <code>optional string candidateactor = 2;</code>
     */
    boolean hasCandidateactor();
    /**
     * <code>optional string candidateactor = 2;</code>
     */
    java.lang.String getCandidateactor();
    /**
     * <code>optional string candidateactor = 2;</code>
     */
    com.google.protobuf.ByteString
    getCandidateactorBytes();

    /**
     * <code>optional int32 rating = 3;</code>
     */
    boolean hasRating();
    /**
     * <code>optional int32 rating = 3;</code>
     */
    int getRating();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
  com.google.protobuf.GeneratedMessage implements
  // @@protoc_insertion_point(message_implements:User)
  UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
                 com.google.protobuf.CodedInputStream input,
                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                     throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userid_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              candidateactor_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rating_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.feiyu.protobuf.UserActorRatingProtos.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.feiyu.protobuf.UserActorRatingProtos.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.feiyu.protobuf.UserActorRatingProtos.User.class, com.feiyu.protobuf.UserActorRatingProtos.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
                                   com.google.protobuf.CodedInputStream input,
                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                       throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userid_;
    /**
     * <code>optional int64 userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 userid = 1;</code>
     */
    public long getUserid() {
      return userid_;
    }

    public static final int CANDIDATEACTOR_FIELD_NUMBER = 2;
    private java.lang.Object candidateactor_;
    /**
     * <code>optional string candidateactor = 2;</code>
     */
    public boolean hasCandidateactor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string candidateactor = 2;</code>
     */
    public java.lang.String getCandidateactor() {
      java.lang.Object ref = candidateactor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          candidateactor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string candidateactor = 2;</code>
     */
    public com.google.protobuf.ByteString
    getCandidateactorBytes() {
      java.lang.Object ref = candidateactor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
        candidateactor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATING_FIELD_NUMBER = 3;
    private int rating_;
    /**
     * <code>optional int32 rating = 3;</code>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 rating = 3;</code>
     */
    public int getRating() {
      return rating_;
    }

    private void initFields() {
      userid_ = 0L;
      candidateactor_ = "";
      rating_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCandidateactorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rating_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCandidateactorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, rating_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(
                                                                          com.google.protobuf.ByteString data)
                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(
                                                                          com.google.protobuf.ByteString data,
                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(
                                                                          byte[] data,
                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(
                                                                          java.io.InputStream input,
                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                              throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseDelimitedFrom(
                                                                                   java.io.InputStream input,
                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                       throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(
                                                                          com.google.protobuf.CodedInputStream input)
                                                                              throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.feiyu.protobuf.UserActorRatingProtos.User parseFrom(
                                                                          com.google.protobuf.CodedInputStream input,
                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                              throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.feiyu.protobuf.UserActorRatingProtos.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
                                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
    com.google.protobuf.GeneratedMessage.Builder<Builder> implements
    // @@protoc_insertion_point(builder_implements:User)
    com.feiyu.protobuf.UserActorRatingProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.feiyu.protobuf.UserActorRatingProtos.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.feiyu.protobuf.UserActorRatingProtos.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
              com.feiyu.protobuf.UserActorRatingProtos.User.class, com.feiyu.protobuf.UserActorRatingProtos.User.Builder.class);
      }

      // Construct using com.feiyu.protobuf.UserActorRatingProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
                      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateactor_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rating_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.feiyu.protobuf.UserActorRatingProtos.internal_static_User_descriptor;
      }

      public com.feiyu.protobuf.UserActorRatingProtos.User getDefaultInstanceForType() {
        return com.feiyu.protobuf.UserActorRatingProtos.User.getDefaultInstance();
      }

      public com.feiyu.protobuf.UserActorRatingProtos.User build() {
        com.feiyu.protobuf.UserActorRatingProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feiyu.protobuf.UserActorRatingProtos.User buildPartial() {
        com.feiyu.protobuf.UserActorRatingProtos.User result = new com.feiyu.protobuf.UserActorRatingProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateactor_ = candidateactor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rating_ = rating_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feiyu.protobuf.UserActorRatingProtos.User) {
          return mergeFrom((com.feiyu.protobuf.UserActorRatingProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feiyu.protobuf.UserActorRatingProtos.User other) {
        if (other == com.feiyu.protobuf.UserActorRatingProtos.User.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasCandidateactor()) {
          bitField0_ |= 0x00000002;
          candidateactor_ = other.candidateactor_;
          onChanged();
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
                               com.google.protobuf.CodedInputStream input,
                               com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                   throws java.io.IOException {
        com.feiyu.protobuf.UserActorRatingProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feiyu.protobuf.UserActorRatingProtos.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userid_ ;
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public long getUserid() {
        return userid_;
      }
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public Builder setUserid(long value) {
        bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object candidateactor_ = "";
      /**
       * <code>optional string candidateactor = 2;</code>
       */
      public boolean hasCandidateactor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string candidateactor = 2;</code>
       */
      public java.lang.String getCandidateactor() {
        java.lang.Object ref = candidateactor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            candidateactor_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string candidateactor = 2;</code>
       */
      public com.google.protobuf.ByteString
      getCandidateactorBytes() {
        java.lang.Object ref = candidateactor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
          candidateactor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string candidateactor = 2;</code>
       */
      public Builder setCandidateactor(
                                       java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        candidateactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidateactor = 2;</code>
       */
      public Builder clearCandidateactor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateactor_ = getDefaultInstance().getCandidateactor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidateactor = 2;</code>
       */
      public Builder setCandidateactorBytes(
                                            com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        candidateactor_ = value;
        onChanged();
        return this;
      }

      private int rating_ ;
      /**
       * <code>optional int32 rating = 3;</code>
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 rating = 3;</code>
       */
      public int getRating() {
        return rating_;
      }
      /**
       * <code>optional int32 rating = 3;</code>
       */
      public Builder setRating(int value) {
        bitField0_ |= 0x00000004;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rating = 3;</code>
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rating_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:User)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
  internal_static_User_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
  internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
  descriptor;
  static {
    java.lang.String[] descriptorData = {
                                         "\n1src/main/resources/protobuf/useractorr" +
                                             "ating.proto\">\n\004User\022\016\n\006userid\030\001 \001(\003\022\026\n\016c" +
                                             "andidateactor\030\002 \001(\t\022\016\n\006rating\030\003 \001(\005B+\n\022c" +
                                             "om.feiyu.protobufB\025UserActorRatingProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
      public com.google.protobuf.ExtensionRegistry assignDescriptors(
                                                                     com.google.protobuf.Descriptors.FileDescriptor root) {
        descriptor = root;
        return null;
      }
    };
    com.google.protobuf.Descriptors.FileDescriptor
    .internalBuildGeneratedFileFrom(descriptorData,
      new com.google.protobuf.Descriptors.FileDescriptor[] {
    }, assigner);
    internal_static_User_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_User_descriptor,
          new java.lang.String[] { "Userid", "Candidateactor", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
